### PR TITLE
Add image service

### PR DESCRIPTION
**Pull request by darinkrauss**
- Reorder export service
- Add missing documentation

### CODE REVIEW

**Comment by darinkrauss** [comment]
All permissions are provided to the services via EC2 Roles.

**Comment by derrickburns** [comment]
@darin I was asking about the docker-compose environment.

**Comment by darinkrauss** [comment]
Sorry, my mistake. They don't. My local computer has AWS configured with a limited access "CLI" IAM account that has the necessary permissions.

If you wish to do this differently, then that would be follow on work not related to this PR.

**Comment by derrickburns** [comment]
I'm not sure how it is not related to this PR.

This PR is for the development repo. Its purpose is to support docker-compose use of the Tidepool services, right? 

Of course, if you mean that the problem existed for other services prior to the image service, then I agree.  

However one can't use the image service in docker compose without credentials being passed in. This PR does not enable that.

We can certainly create a separate PR to solve the problem for all three afflicted services at once. I can do that.

**Comment by darinkrauss** [comment]
Sounds great! Thanks!

**Comment by derrickburns** [comment]
I fixed all the credentials passing. This PR 

LGTM

**Pull request merged**
